src/status_chart.ts: Add moreHistoryButton, lessHistoryButton.
Fixes error TS2531: Object is possibly 'null'.
(We know that they always exist.)

Fixes error TS2339: Property 'disabled' does not exist on type 'HTMLElement'.
(We know that they're always buttons.)