src/status_chart.ts: `status_chart` etc. should be separate variables.
Instead of being added as properties of `window`.

Fixes error TS2339: Property 'status_chart' does not exist on type 'Window & typeof globalThis'.