src/status_chart.ts: Add parameter types to update_chart_timeframe().
Fixes:
error TS7006: Parameter 'chart' implicitly has an 'any' type.
error TS7006: Parameter 'idx' implicitly has an 'any' type.

Using `typeof status_chart` instead of `Chart` avoids:
error TS2379: Argument of type 'Chart<X>' is not assignable to parameter of type 'Chart<Y>' [...]
  The types of 'config.data' are incompatible between these types.