src/status_chart.ts: Use const assertions for daily_keys, weekly_keys.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions

Fixes:
error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'DailyRow'.
  No index signature with a parameter of type 'string' was found on type 'DailyRow'.
error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'WeeklyRow'.
  No index signature with a parameter of type 'string' was found on type 'WeeklyRow'.